---
version: '3.7'

services:
  redis:
    image: docker.io/redis:alpine@sha256:2c8839911829aac720d41690edc07c0aff8385294fccd3a892af46d1a83b1ac0
    command: "/etc/redis.conf"
    networks:
    - internal
    restart: unless-stopped
    volumes:
    - ./redis.conf:/etc/redis.conf:ro
    - type: volume
      source: redis-socket
      target: /tmp/redis

networks:
  # The default network is a bridge that connects containers to the outside
  # world.  This is used for ingress.
  default:

  # The internal network is used solely for container-container communication,
  # and is sandboxed by the `{ internal: true }` configuration here.
  # Only those containers which are attached to this network will be able to
  # communicate with the outside world.
  internal:
    internal: true

  scanning:
    external: true
    name: host

volumes:
  redis-socket:
    driver_opts:
      type: tmpfs
      device: tmpfs
